"""Render the dated findings doc from 01-03's CSVs. No number below is typed by hand.

Follows the repo's `analysis/audits/<topic>_audit_<YYYY-MM-DD>.md` convention: a dated,
point-in-time file, never edited after the fact -- a later pass writes a new dated file.

Run from the repo root, AFTER 01, 02 and 03:
    python analysis/opa_split_equity/04_generate_findings.py
"""
from datetime import date
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "out"
AUDITS = ROOT / "analysis" / "audits"
TODAY = date.today().isoformat()
DEST = AUDITS / f"opa_land_building_split_audit_{TODAY}.md"


def usd(x, decimals=0):
    s = f"${abs(x):,.{decimals}f}"
    return f"-{s}" if x < 0 else s


def pct(x, decimals=0):
    return f"{x:.{decimals}f}%"


def main() -> None:
    basis = pd.read_csv(OUT / "land_ratio_measurement_basis.csv", index_col="tax_year")
    who_moves = pd.read_csv(OUT / "who_can_move_by_exemption_kind.csv", index_col=["alternative", "exemption_kind"])
    cohort_tot = pd.read_csv(OUT / "abatement_cohort_totals.csv", index_col=["cohort", "alternative"])
    rep = pd.read_csv(OUT / "witness_representativeness.csv", index_col=0)
    by_inc = pd.read_csv(OUT / "lot_ratio_by_income_tercile.csv", index_col="stratum")
    by_min = pd.read_csv(OUT / "lot_ratio_by_minority_tercile.csv", index_col="stratum")
    rw = pd.read_csv(OUT / "reweighted_lot_ratio.csv").iloc[0]
    at_lot = pd.read_csv(OUT / "full_abatement_at_lot_price.csv").iloc[0]
    disp = pd.read_csv(OUT / "effective_rate_dispersion.csv", index_col=0)
    oof = pd.read_csv(OUT / "s5_out_of_fold_check.csv", index_col=0)

    ty = 2026
    n_at_20 = basis.loc[ty, "pct_at_0.200_full_value"]
    n_full = int(cohort_tot.loc[("full abatement", "s5 (sales-based)"), "n"])
    tax_full = cohort_tot.loc[("full abatement", "s5 (sales-based)"), "current_tax_usd"]
    hs_n = int(who_moves.loc[("s5 (sales-based)", "homestead"), "n_parcels"])
    hs_moved = int(who_moves.loc[("s5 (sales-based)", "homestead"), "n_moved"])
    bs_n = int(who_moves.loc[("s5 (sales-based)", "building_share"), "n_parcels"])
    bs_moved_pct = who_moves.loc[("s5 (sales-based)", "building_share"), "pct_moved"]

    s5_net = cohort_tot.loc[("full abatement", "s5 (sales-based)"), "net_change_usd"]
    s5_pct = cohort_tot.loc[("full abatement", "s5 (sales-based)"), "net_pct_of_cohort_tax"]

    text = f"""# Does OPA's 20% land-share default distort tax burdens on abated homes?

**Date:** {TODAY}. Point-in-time findings; a later pass writes a new dated file rather than
editing this one. Generated by `analysis/opa_split_equity/0{{1,2,3}}_*.py`; every number below
is read from `analysis/opa_split_equity/out/*.csv`, not typed into this file.

## Question

OPA gives most improved Philadelphia parcels a land share of exactly 20% of assessed value.
The Homestead Exemption and the 10-year construction abatement are both applied to the
BUILDING line, which is the reason a fixed, inaccurate split can matter for tax burdens even
though the total assessment and the millage are correct. This asks whether it does, and for
whom.

## The default is not universal, and it is least common where the most value sits

{pct(n_at_20)} of improved parcels carry a land share within 0.05 points of exactly 20%
(measured on full value -- taxable plus exempt dollars; measuring on the taxable columns
alone understates this because the Homestead Exemption comes off the building line and pushes
a homesteaded parcel's TAXABLE share away from 0.200 even though OPA assigned it 0.200). See
`out/land_ratio_by_category_ty2026.csv` and `out/land_ratio_by_value_decile_ty2026.csv` for the
breakdown: the default is least common on commercial and industrial parcels and in the
highest-value decile, where OPA appears to assess land individually rather than by rule.

## Homestead is unaffected under today's single rate; the construction abatement is the exposed channel

Re-splitting every parcel's land and building inside OPA's own total (rate and total held
fixed, so a bill can only move where an exemption depends on the split):

- **{hs_moved} of {hs_n:,}** Homestead-Exemption parcels moved. The exemption is a flat
  `min($100K, total)`; which line it nets against doesn't change that. (53 Pa.C.S. Sec. 8583(c)'s
  building-first order only matters once land and building are taxed at *different* rates --
  a split-rate reform question, not a fact about today's bills.)
- **{bs_moved_pct:.1f}% of {bs_n:,}** parcels whose exemption sits on the building line (the
  construction abatement) moved. This is the entire channel through which the split affects
  current bills.

The cohort here is restricted to `schedule_type`s the repo's classifier confirms are
construction abatements ({n_full:,} full abatements, paying {usd(tax_full)}/year today) --
excluding `non_abatement_relief`, an unidentified program whose exempt share can RISE at
reassessment, which an abatement's cannot.

## The market check: 440 abated homes' own pre-construction lot sale

Rather than infer a land value from a modeled surface or a tract aggregate, {int(rep.loc['witnessed subset', 'n'])} full \
abatements have their own recorded arm's-length lot sale on file (sold vacant or bought and torn \
down, time-adjusted to the TY2026 valuation date) -- the parcel's own answer to what its land was \
worth as vacant ground.

**This subset is not representative and is reweighted before drawing a headline number.** It skews \
toward lower-income, more-recently-built parcels (median tract income \
{usd(rep.loc['witnessed subset', 'median_income_usd'])} vs {usd(rep.loc['full abatement cohort', 'median_income_usd'])} \
for the full cohort; median minority share {rep.loc['witnessed subset', 'median_minority_pct']:.0f}% \
vs {rep.loc['full abatement cohort', 'median_minority_pct']:.0f}%). Reweighting to the full cohort's \
(income tercile x property category) mix (covering {pct(100 * rw['cohort_share_in_witnessed_cells'])} \
of the cohort's value across {int(rw['cells_witnessed'])} of {int(rw['cells_in_cohort'])} cells):

| | OPA land / lot price | s5 land / lot price | lot price as % of total |
|---|---|---|---|
| Unweighted median | {rw['unweighted_opa_over_lot_median']:.2f} | {rw['unweighted_s5_over_lot_median']:.2f} | {pct(100 * rw['unweighted_lot_share_median'])} |
| Reweighted to cohort mix | {rw['reweighted_opa_over_lot_median']:.2f} | {rw['reweighted_s5_over_lot_median']:.2f} | {pct(100 * rw['reweighted_lot_share_median'])} |

Reweighted, the 20% default is close to right ON AVERAGE ({rw['reweighted_opa_over_lot_median']:.2f}x
the witnessed lot price) -- but that average hides a sharp pattern by neighborhood:

| Tract stratum | n | OPA land / lot price (median) | Lot price as % of total |
|---|---|---|---|
| Low income | {int(by_inc.loc['low_income','n'])} | {by_inc.loc['low_income','opa_over_lot_median']:.2f} | {pct(100*by_inc.loc['low_income','lot_share_of_total_median'])} |
| Mid income | {int(by_inc.loc['mid_income','n'])} | {by_inc.loc['mid_income','opa_over_lot_median']:.2f} | {pct(100*by_inc.loc['mid_income','lot_share_of_total_median'])} |
| High income | {int(by_inc.loc['high_income','n'])} | {by_inc.loc['high_income','opa_over_lot_median']:.2f} | {pct(100*by_inc.loc['high_income','lot_share_of_total_median'])} |
| Most non-white | {int(by_min.loc['most_nonwhite','n'])} | {by_min.loc['most_nonwhite','opa_over_lot_median']:.2f} | {pct(100*by_min.loc['most_nonwhite','lot_share_of_total_median'])} |
| Whitest | {int(by_min.loc['whitest','n'])} | {by_min.loc['whitest','opa_over_lot_median']:.2f} | {pct(100*by_min.loc['whitest','lot_share_of_total_median'])} |

OPA's 20% overstates land value (and so overtaxes the improvement-exempt home) by roughly
{pct(100 * (by_inc.loc['low_income','opa_over_lot_median'] - 1))} in low-income tracts and is close
to or below the lot price in high-income tracts -- the opposite gradient from a modeled land surface, which
(having no witness of its own in these cells) cannot see this pattern and instead follows lot
size.

**In dollars, this cuts a different way than the ratio alone suggests.** Pricing land at each
witnessed home's own lot sale (capped at the parcel's own total):

- **{pct(at_lot['pct_pay_less'])} of the {int(at_lot['n'])} witnessed homes would pay LESS** than
  they do today (median change {usd(at_lot['median_change_usd'])}) -- consistent with the default
  overstating land value for most of this (disproportionately lower-income) subset.
- But the net dollar change across the subset is **{usd(at_lot['net_change_usd'])}**
  ({pct(at_lot['net_pct_of_cohort_tax'])} of the subset's {usd(at_lot['current_tax_usd'])} current
  tax) -- positive, not negative -- because a smaller number of higher-value witnessed parcels
  would pay substantially more, and that tail outweighs the many small cuts.

**The default erases most of the real spread in what these homes' land is worth.** Today,
effective rate (mills of total assessed value actually billed) for the witnessed cohort runs
{disp.loc['today (OPA 20% default)','p10_mills']:.2f}-{disp.loc['today (OPA 20% default)','p90_mills']:.2f}
mills (p10-p90, ratio {disp.loc['today (OPA 20% default)','p90_over_p10']:.1f}x). Priced at each
home's own lot sale it would run
{disp.loc['at own recorded lot price','p10_mills']:.2f}-{disp.loc['at own recorded lot price','p90_mills']:.2f}
mills (ratio {disp.loc['at own recorded lot price','p90_over_p10']:.1f}x) -- roughly double the spread.
That flattening, not a single net dollar figure, is the clearest and most robust finding here:
whichever direction the average moves, the 20% default treats abated homes with very different
land values as if they were the same.

## The two modeled-surface alternatives bracket without resolving the aggregate sign

On the full cohort ({n_full:,} parcels, not just the 440 witnessed): the sales-based surface
(s5) implies a net **{usd(s5_net)}** ({pct(s5_pct)} of cohort tax) shift, concentrated in large
multi-family parcels and high-value parcels s5 has never had a nearby sale to check (OPA already
assesses those individually rather than by the 20% rule, which is exactly where a lot-area-based
model is least trustworthy). s5 is also shown circular on its own witnessed parcels: painted
(in-sample) land value has COD {oof.loc['s5 painted (in-sample) / lot','cod_pct']:.0f}% against the
lot price it was partly fit to explain; scored out-of-fold (a fold that never saw the parcel) the
COD widens to {oof.loc['s5 out-of-fold / lot','cod_pct']:.0f}%, still centered near the lot price
(median {oof.loc['s5 out-of-fold / lot','median']:.2f}) and still tighter than OPA's own
(COD {oof.loc['OPA / lot','cod_pct']:.0f}%, median {oof.loc['OPA / lot','median']:.2f}), but not
tight enough to bill an individual parcel from.

LYCD (zone-rate) moves in the opposite direction from s5 on this cohort; it is not treated as a
vote on direction here (`02_split_vs_alternatives.py`'s docstring has the reasoning) -- it
redistributes OPA's own 20% by lot size and cannot see anything the witnessed lot sales or s5
haven't already said about where land is actually worth more or less.

## Bottom line

- **Homestead:** not affected under Philadelphia's single millage. This is a fact about
  current bills, not about a future split-rate reform, where the building-first order becomes
  load-bearing.
- **The construction abatement is the real channel**, and it is real: {bs_moved_pct:.0f}% of the
  cohort's bill depends on the land/building split.
- **The error is regressive among abated homes**, on the only direct market evidence available
  (their own lot sales): OPA's flat 20% overstates land value more in lower-income,
  higher-minority tracts.
- **The net dollar sign is not resolved.** The witnessed subset's own dollars lean slightly
  positive (net {usd(at_lot['net_change_usd'])}) because a minority of high-value parcels
  dominate the sum even though most parcels would pay less; the full-cohort modeled estimate
  (s5) leans the other way in aggregate ({usd(s5_net)}) but is least trustworthy exactly where
  it has no witness. Do not report a single citywide net-revenue-shift number from either
  source without that caveat attached.
"""

    AUDITS.mkdir(parents=True, exist_ok=True)
    DEST.write_text(text, encoding="utf-8")
    print(f"wrote {DEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
